# project source
TOPNAME = PvuTop
VSRCS += $(shell find $(abspath ./vsrc) -name "*.sv")
CSRCS += $(shell find $(abspath ./csrc) -name "*.cpp")
CONFIG_H = config.h

# The exact-reference regression uses the checked-out SoftPosit source. Its
# headers use C++ aggregate initializers, so compile the small p32-only subset
# as C++ rather than relying on the upstream all-target (which also builds
# unrelated formats). No SoftPosit source is copied into this repository.
SOFTPOSIT_ROOT ?= /root/SoftPosit
SOFTPOSIT_REF_DIR ?= build/softposit-ref
SOFTPOSIT_REF_LIB := $(SOFTPOSIT_REF_DIR)/libsoftposit-ref.a
SOFTPOSIT_REF_SRCS := \
	$(SOFTPOSIT_ROOT)/source/s_addMagsP32.c \
	$(SOFTPOSIT_ROOT)/source/s_subMagsP32.c \
	$(SOFTPOSIT_ROOT)/source/s_mulAddP32.c \
	$(SOFTPOSIT_ROOT)/source/p32_add.c \
	$(SOFTPOSIT_ROOT)/source/p32_sub.c \
	$(SOFTPOSIT_ROOT)/source/p32_mul.c \
	$(SOFTPOSIT_ROOT)/source/p32_mulAdd.c \
	$(SOFTPOSIT_ROOT)/source/p32_div.c \
	$(SOFTPOSIT_ROOT)/source/p32_to_pX2.c \
	$(SOFTPOSIT_ROOT)/source/p32_to_i32.c \
	$(SOFTPOSIT_ROOT)/source/i32_to_p32.c \
	$(SOFTPOSIT_ROOT)/source/c_convertDecToPosit32.c \
	$(SOFTPOSIT_ROOT)/source/c_convertPosit32ToDec.c
SOFTPOSIT_REF_CXXFLAGS := -std=c++17 -O2 -DSOFTPOSIT_FAST_INT64 -DINLINE_LEVEL=5 \
	-I$(SOFTPOSIT_ROOT)/build/Linux-x86_64-GCC \
	-I$(SOFTPOSIT_ROOT)/source/8086-SSE \
	-I$(SOFTPOSIT_ROOT)/source/include

# verilator flags
VERILATOR_FLAGS += -Wall --cc --trace --exe --build --top-module $(TOPNAME)
VERILATOR_FLAGS += -Wno-DECLFILENAME -Wno-PINCONNECTEMPTY -Wno-UNUSEDSIGNAL -Wno-UNOPTFLAT
VERILATOR_FLAGS += --threads-dpi all
VERILATOR_FLAGS += -j 16

include .config

ifeq ($(CONFIG_PVU_PROTOCOL_REGRESSION),y)
VERILATOR_FLAGS += -CFLAGS "$(SOFTPOSIT_REF_CXXFLAGS)"
VERILATOR_FLAGS += -LDFLAGS "$(abspath $(SOFTPOSIT_REF_LIB))"
PVU_RUN_PREREQS += $(SOFTPOSIT_REF_LIB)
endif

$(CONFIG_H): .config
	@echo "/* Auto-generated by Makefile from .config */" > $(CONFIG_H)
	@echo "#ifndef CONFIG_H" >> $(CONFIG_H)
	@echo "#define CONFIG_H" >> $(CONFIG_H)
	@echo "" >> $(CONFIG_H)
	@awk 'BEGIN { FS="="; OFS=" "; } \
		/^[^#]/ { \
			if ($$2 == "y") { \
				print "#define", $$1, "1"; \
			} else if ($$2 == "n" || $$2 == "") { \
				print "#define", $$1, "0"; \
			} \
		}' .config >> $(CONFIG_H)

	@echo "#endif // CONFIG_H" >> $(CONFIG_H)


verilog:
	export JAVA_OPTS="-Xmx16G -Xms8G -XX:+UseG1GC -XX:G1HeapRegionSize=32M -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8" && \
	sbt -v -no-colors \
		-J-Xmx16G -J-Xms8G \
		-J-XX:+UseG1GC \
		-J-XX:G1HeapRegionSize=32M \
		-J-XX:MaxGCPauseMillis=200 \
		-J-XX:ParallelGCThreads=8 \
		-Dsbt.task.timings=true \
		-Dsbt.ci=true \
		-DmaxThreads=8 \
		"runMain pvu.Elaborate"
	python3 clean_line.py

$(SOFTPOSIT_REF_LIB): $(SOFTPOSIT_REF_SRCS)
	@mkdir -p $(SOFTPOSIT_REF_DIR)
	cd $(SOFTPOSIT_REF_DIR) && g++ $(SOFTPOSIT_REF_CXXFLAGS) -x c++ -c $(SOFTPOSIT_REF_SRCS)
	ar crs $@ $(SOFTPOSIT_REF_DIR)/*.o

run:${CSRCS} ${VSRCS} $(PVU_RUN_PREREQS)
	verilator ${VERILATOR_FLAGS} ${CSRCS} ${VSRCS}
	./obj_dir/VPvuTop

wave:
	gtkwave pvu_top_wave.vcd
	
menuconfig:
	menuconfig
	make config.h

count:
	@echo "Number of Scala files:"
	@echo $(shell find . -type f -name "*.scala" | wc -l)
	@echo "Total lines of Scala code:"
	@echo $(shell find src -name "*.scala" -type f | xargs cat | wc -l)
	@echo "Total lines of Verilog code:"
	@echo $(shell find vsrc -name "*.sv" -type f | xargs cat | wc -l)


debug:
	make verilog
	make run

